// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: cinema_service_v1_messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Time in format RFC3339, time must be in UTC
	// example: 2023-11-10T23:00:00Z
	FormattedTimestamp string `protobuf:"bytes,1,opt,name=formattedTimestamp,json=formatted_timestamp,proto3" json:"formattedTimestamp,omitempty"`
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetFormattedTimestamp() string {
	if x != nil {
		return x.FormattedTimestamp
	}
	return ""
}

type GetMoviesScreeningsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaId    int32      `protobuf:"varint,1,opt,name=cinemaId,json=cinema_id,proto3" json:"cinemaId,omitempty"`
	StartPeriod *Timestamp `protobuf:"bytes,2,opt,name=startPeriod,json=start_period,proto3" json:"startPeriod,omitempty"`
	EndPeriod   *Timestamp `protobuf:"bytes,3,opt,name=endPeriod,json=end_period,proto3" json:"endPeriod,omitempty"`
}

func (x *GetMoviesScreeningsRequest) Reset() {
	*x = GetMoviesScreeningsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviesScreeningsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesScreeningsRequest) ProtoMessage() {}

func (x *GetMoviesScreeningsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesScreeningsRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesScreeningsRequest) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetMoviesScreeningsRequest) GetCinemaId() int32 {
	if x != nil {
		return x.CinemaId
	}
	return 0
}

func (x *GetMoviesScreeningsRequest) GetStartPeriod() *Timestamp {
	if x != nil {
		return x.StartPeriod
	}
	return nil
}

func (x *GetMoviesScreeningsRequest) GetEndPeriod() *Timestamp {
	if x != nil {
		return x.EndPeriod
	}
	return nil
}

type GetMoviesScreeningsInCitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// cities ids empty, returns all screenings without city id matching, for multiple values use ',' as separator
	CitiesIds   *string    `protobuf:"bytes,1,opt,name=citiesIds,json=cities_ids,proto3,oneof" json:"citiesIds,omitempty"`
	StartPeriod *Timestamp `protobuf:"bytes,2,opt,name=startPeriod,json=start_period,proto3" json:"startPeriod,omitempty"`
	EndPeriod   *Timestamp `protobuf:"bytes,3,opt,name=endPeriod,json=end_period,proto3" json:"endPeriod,omitempty"`
}

func (x *GetMoviesScreeningsInCitiesRequest) Reset() {
	*x = GetMoviesScreeningsInCitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMoviesScreeningsInCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMoviesScreeningsInCitiesRequest) ProtoMessage() {}

func (x *GetMoviesScreeningsInCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMoviesScreeningsInCitiesRequest.ProtoReflect.Descriptor instead.
func (*GetMoviesScreeningsInCitiesRequest) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetMoviesScreeningsInCitiesRequest) GetCitiesIds() string {
	if x != nil && x.CitiesIds != nil {
		return *x.CitiesIds
	}
	return ""
}

func (x *GetMoviesScreeningsInCitiesRequest) GetStartPeriod() *Timestamp {
	if x != nil {
		return x.StartPeriod
	}
	return nil
}

func (x *GetMoviesScreeningsInCitiesRequest) GetEndPeriod() *Timestamp {
	if x != nil {
		return x.EndPeriod
	}
	return nil
}

type Price struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The price value in minimum currency units, for example 10010, is 100$ and 10 penny
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Price) Reset() {
	*x = Price{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Price) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PreviewScreening struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID         int32    `protobuf:"varint,1,opt,name=movieID,json=movie_id,proto3" json:"movieID,omitempty"`
	ScreeningsTypes []string `protobuf:"bytes,2,rep,name=screeningsTypes,json=screenings_types,proto3" json:"screeningsTypes,omitempty"`
	HallsTypes      []string `protobuf:"bytes,3,rep,name=hallsTypes,json=halls_types,proto3" json:"hallsTypes,omitempty"`
}

func (x *PreviewScreening) Reset() {
	*x = PreviewScreening{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreviewScreening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewScreening) ProtoMessage() {}

func (x *PreviewScreening) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewScreening.ProtoReflect.Descriptor instead.
func (*PreviewScreening) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PreviewScreening) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *PreviewScreening) GetScreeningsTypes() []string {
	if x != nil {
		return x.ScreeningsTypes
	}
	return nil
}

func (x *PreviewScreening) GetHallsTypes() []string {
	if x != nil {
		return x.HallsTypes
	}
	return nil
}

// Unique set of cinema screenings (unique by movie_id)
type PreviewScreenings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Screenings []*PreviewScreening `protobuf:"bytes,1,rep,name=screenings,proto3" json:"screenings,omitempty"`
}

func (x *PreviewScreenings) Reset() {
	*x = PreviewScreenings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreviewScreenings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewScreenings) ProtoMessage() {}

func (x *PreviewScreenings) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewScreenings.ProtoReflect.Descriptor instead.
func (*PreviewScreenings) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PreviewScreenings) GetScreenings() []*PreviewScreening {
	if x != nil {
		return x.Screenings
	}
	return nil
}

type GetScreeningsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaId    int32      `protobuf:"varint,1,opt,name=cinemaId,json=cinema_id,proto3" json:"cinemaId,omitempty"`
	MovieID     int32      `protobuf:"varint,2,opt,name=movieID,json=movie_id,proto3" json:"movieID,omitempty"`
	StartPeriod *Timestamp `protobuf:"bytes,3,opt,name=startPeriod,json=start_period,proto3" json:"startPeriod,omitempty"`
	EndPeriod   *Timestamp `protobuf:"bytes,4,opt,name=endPeriod,json=end_period,proto3" json:"endPeriod,omitempty"`
}

func (x *GetScreeningsRequest) Reset() {
	*x = GetScreeningsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScreeningsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScreeningsRequest) ProtoMessage() {}

func (x *GetScreeningsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScreeningsRequest.ProtoReflect.Descriptor instead.
func (*GetScreeningsRequest) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetScreeningsRequest) GetCinemaId() int32 {
	if x != nil {
		return x.CinemaId
	}
	return 0
}

func (x *GetScreeningsRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *GetScreeningsRequest) GetStartPeriod() *Timestamp {
	if x != nil {
		return x.StartPeriod
	}
	return nil
}

func (x *GetScreeningsRequest) GetEndPeriod() *Timestamp {
	if x != nil {
		return x.EndPeriod
	}
	return nil
}

type Screening struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScreeningID   int64      `protobuf:"varint,1,opt,name=screeningID,json=screening_id,proto3" json:"screeningID,omitempty"`
	MovieID       int32      `protobuf:"varint,2,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
	ScreeningType string     `protobuf:"bytes,3,opt,name=screeningType,json=screening_type,proto3" json:"screeningType,omitempty"`
	StartTime     *Timestamp `protobuf:"bytes,4,opt,name=startTime,json=start_time,proto3" json:"startTime,omitempty"`
	HallID        int32      `protobuf:"varint,5,opt,name=hallID,json=hall_id,proto3" json:"hallID,omitempty"`
	TicketPrice   *Price     `protobuf:"bytes,6,opt,name=ticketPrice,json=ticket_price,proto3" json:"ticketPrice,omitempty"`
}

func (x *Screening) Reset() {
	*x = Screening{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screening) ProtoMessage() {}

func (x *Screening) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screening.ProtoReflect.Descriptor instead.
func (*Screening) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Screening) GetScreeningID() int64 {
	if x != nil {
		return x.ScreeningID
	}
	return 0
}

func (x *Screening) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *Screening) GetScreeningType() string {
	if x != nil {
		return x.ScreeningType
	}
	return ""
}

func (x *Screening) GetStartTime() *Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Screening) GetHallID() int32 {
	if x != nil {
		return x.HallID
	}
	return 0
}

func (x *Screening) GetTicketPrice() *Price {
	if x != nil {
		return x.TicketPrice
	}
	return nil
}

type Screenings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Screenings []*Screening `protobuf:"bytes,1,rep,name=screenings,proto3" json:"screenings,omitempty"`
}

func (x *Screenings) Reset() {
	*x = Screenings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screenings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screenings) ProtoMessage() {}

func (x *Screenings) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screenings.ProtoReflect.Descriptor instead.
func (*Screenings) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Screenings) GetScreenings() []*Screening {
	if x != nil {
		return x.Screenings
	}
	return nil
}

type GetCinemasInCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId int32 `protobuf:"varint,1,opt,name=cityId,json=city_id,proto3" json:"cityId,omitempty"`
}

func (x *GetCinemasInCityRequest) Reset() {
	*x = GetCinemasInCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCinemasInCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCinemasInCityRequest) ProtoMessage() {}

func (x *GetCinemasInCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCinemasInCityRequest.ProtoReflect.Descriptor instead.
func (*GetCinemasInCityRequest) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GetCinemasInCityRequest) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

type Coordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latityde  float64 `protobuf:"fixed64,1,opt,name=latityde,proto3" json:"latityde,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Coordinates) GetLatityde() float64 {
	if x != nil {
		return x.Latityde
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Cinema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaID    int32        `protobuf:"varint,1,opt,name=cinemaID,json=cinema_id,proto3" json:"cinemaID,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address     string       `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Coordinates *Coordinates `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *Cinema) Reset() {
	*x = Cinema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cinema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cinema) ProtoMessage() {}

func (x *Cinema) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cinema.ProtoReflect.Descriptor instead.
func (*Cinema) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Cinema) GetCinemaID() int32 {
	if x != nil {
		return x.CinemaID
	}
	return 0
}

func (x *Cinema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cinema) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Cinema) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type Cinemas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cinemas []*Cinema `protobuf:"bytes,1,rep,name=cinemas,proto3" json:"cinemas,omitempty"`
}

func (x *Cinemas) Reset() {
	*x = Cinemas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cinemas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cinemas) ProtoMessage() {}

func (x *Cinemas) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cinemas.ProtoReflect.Descriptor instead.
func (*Cinemas) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *Cinemas) GetCinemas() []*Cinema {
	if x != nil {
		return x.Cinemas
	}
	return nil
}

type City struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityID int32  `protobuf:"varint,1,opt,name=cityID,json=city_id,proto3" json:"cityID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *City) Reset() {
	*x = City{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *City) GetCityID() int32 {
	if x != nil {
		return x.CityID
	}
	return 0
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Cities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cities []*City `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
}

func (x *Cities) Reset() {
	*x = Cities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cities) ProtoMessage() {}

func (x *Cities) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cities.ProtoReflect.Descriptor instead.
func (*Cities) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *Cities) GetCities() []*City {
	if x != nil {
		return x.Cities
	}
	return nil
}

type Hall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HallID   int32  `protobuf:"varint,1,opt,name=hallID,json=hall_id,proto3" json:"hallID,omitempty"`
	HallSize uint32 `protobuf:"varint,2,opt,name=hallSize,json=hall_size,proto3" json:"hallSize,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Hall) Reset() {
	*x = Hall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hall) ProtoMessage() {}

func (x *Hall) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hall.ProtoReflect.Descriptor instead.
func (*Hall) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *Hall) GetHallID() int32 {
	if x != nil {
		return x.HallID
	}
	return 0
}

func (x *Hall) GetHallSize() uint32 {
	if x != nil {
		return x.HallSize
	}
	return 0
}

func (x *Hall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Halls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Halls []*Hall `protobuf:"bytes,1,rep,name=halls,proto3" json:"halls,omitempty"`
}

func (x *Halls) Reset() {
	*x = Halls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Halls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Halls) ProtoMessage() {}

func (x *Halls) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Halls.ProtoReflect.Descriptor instead.
func (*Halls) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *Halls) GetHalls() []*Hall {
	if x != nil {
		return x.Halls
	}
	return nil
}

type GetCinemaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaId int32 `protobuf:"varint,1,opt,name=cinemaId,proto3" json:"cinemaId,omitempty"`
}

func (x *GetCinemaRequest) Reset() {
	*x = GetCinemaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCinemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCinemaRequest) ProtoMessage() {}

func (x *GetCinemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCinemaRequest.ProtoReflect.Descriptor instead.
func (*GetCinemaRequest) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *GetCinemaRequest) GetCinemaId() int32 {
	if x != nil {
		return x.CinemaId
	}
	return 0
}

type GetHallsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// for multiple values use ',' separator
	HallsIds string `protobuf:"bytes,1,opt,name=hallsIds,json=halls_ids,proto3" json:"hallsIds,omitempty"`
}

func (x *GetHallsRequest) Reset() {
	*x = GetHallsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHallsRequest) ProtoMessage() {}

func (x *GetHallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHallsRequest.ProtoReflect.Descriptor instead.
func (*GetHallsRequest) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *GetHallsRequest) GetHallsIds() string {
	if x != nil {
		return x.HallsIds
	}
	return ""
}

type GetHallConfigurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HallId int32 `protobuf:"varint,1,opt,name=hallId,json=hall_id,proto3" json:"hallId,omitempty"`
}

func (x *GetHallConfigurationRequest) Reset() {
	*x = GetHallConfigurationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHallConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHallConfigurationRequest) ProtoMessage() {}

func (x *GetHallConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHallConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetHallConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *GetHallConfigurationRequest) GetHallId() int32 {
	if x != nil {
		return x.HallId
	}
	return 0
}

type Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row      int32   `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Seat     int32   `protobuf:"varint,2,opt,name=seat,proto3" json:"seat,omitempty"`
	GridPosX float32 `protobuf:"fixed32,3,opt,name=grid_pos_x,json=gridPosX,proto3" json:"grid_pos_x,omitempty"`
	GridPosY float32 `protobuf:"fixed32,4,opt,name=grid_pos_y,json=gridPosY,proto3" json:"grid_pos_y,omitempty"`
}

func (x *Place) Reset() {
	*x = Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *Place) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Place) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *Place) GetGridPosX() float32 {
	if x != nil {
		return x.GridPosX
	}
	return 0
}

func (x *Place) GetGridPosY() float32 {
	if x != nil {
		return x.GridPosY
	}
	return 0
}

type HallConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Place []*Place `protobuf:"bytes,1,rep,name=place,proto3" json:"place,omitempty"`
}

func (x *HallConfiguration) Reset() {
	*x = HallConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HallConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HallConfiguration) ProtoMessage() {}

func (x *HallConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HallConfiguration.ProtoReflect.Descriptor instead.
func (*HallConfiguration) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{21}
}

func (x *HallConfiguration) GetPlace() []*Place {
	if x != nil {
		return x.Place
	}
	return nil
}

type GetCinemaHalls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaId int32 `protobuf:"varint,1,opt,name=CinemaId,json=cinema_id,proto3" json:"CinemaId,omitempty"`
}

func (x *GetCinemaHalls) Reset() {
	*x = GetCinemaHalls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_service_v1_messages_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCinemaHalls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCinemaHalls) ProtoMessage() {}

func (x *GetCinemaHalls) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_service_v1_messages_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCinemaHalls.ProtoReflect.Descriptor instead.
func (*GetCinemaHalls) Descriptor() ([]byte, []int) {
	return file_cinema_service_v1_messages_proto_rawDescGZIP(), []int{22}
}

func (x *GetCinemaHalls) GetCinemaId() int32 {
	if x != nil {
		return x.CinemaId
	}
	return 0
}

var File_cinema_service_v1_messages_proto protoreflect.FileDescriptor

var file_cinema_service_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x76, 0x31, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x3c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x2f, 0x0a, 0x12, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0xb1, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x53, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x12, 0x3c, 0x0a, 0x0b,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x6e,
	0x64, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x22, 0xce, 0x01, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x73, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x43, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x09, 0x63,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0a, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x3c, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x38, 0x0a,
	0x09, 0x65, 0x6e, 0x64, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x6e, 0x64,
	0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x49, 0x64, 0x73, 0x22, 0x1d, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x79, 0x0a, 0x10, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x53,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x5f, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x0f, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x73, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0a, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22,
	0x55, 0x0a, 0x11, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x40, 0x0a, 0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e,
	0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x65,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xc6, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x07,
	0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d,
	0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x3c, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22,
	0xfd, 0x01, 0x0a, 0x09, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a,
	0x0b, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0d, 0x73,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x06,
	0x68, 0x61, 0x6c, 0x6c, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x61,
	0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x69, 0x6e,
	0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22,
	0x47, 0x0a, 0x0a, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x39, 0x0a,
	0x0a, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x73, 0x63,
	0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x32, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x73, 0x49, 0x6e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x22, 0x47, 0x0a, 0x0b,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x79, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c,
	0x61, 0x74, 0x69, 0x74, 0x79, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67,
	0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x06, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x12, 0x1b, 0x0a, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x07, 0x43, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x07,
	0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x73, 0x22, 0x33, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12,
	0x17, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x06,
	0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x06, 0x63, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x22, 0x64, 0x0a, 0x04, 0x48, 0x61, 0x6c, 0x6c, 0x12, 0x17, 0x0a, 0x06,
	0x68, 0x61, 0x6c, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x61,
	0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x68, 0x61, 0x6c, 0x6c, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x68, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x33, 0x0a, 0x05, 0x48, 0x61,
	0x6c, 0x6c, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x05, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x22,
	0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x22,
	0x2e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x08, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x49, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x61, 0x6c, 0x6c, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x22,
	0x36, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x06, 0x68, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x68, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72,
	0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x73, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x0a, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x70,
	0x6f, 0x73, 0x5f, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x67, 0x72, 0x69, 0x64,
	0x50, 0x6f, 0x73, 0x58, 0x12, 0x1c, 0x0a, 0x0a, 0x67, 0x72, 0x69, 0x64, 0x5f, 0x70, 0x6f, 0x73,
	0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x67, 0x72, 0x69, 0x64, 0x50, 0x6f,
	0x73, 0x59, 0x22, 0x40, 0x0a, 0x11, 0x48, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x05, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x22, 0x2d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x48, 0x61, 0x6c, 0x6c, 0x73, 0x12, 0x1b, 0x0a, 0x08, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61,
	0x5f, 0x69, 0x64, 0x42, 0x1a, 0x5a, 0x18, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cinema_service_v1_messages_proto_rawDescOnce sync.Once
	file_cinema_service_v1_messages_proto_rawDescData = file_cinema_service_v1_messages_proto_rawDesc
)

func file_cinema_service_v1_messages_proto_rawDescGZIP() []byte {
	file_cinema_service_v1_messages_proto_rawDescOnce.Do(func() {
		file_cinema_service_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_cinema_service_v1_messages_proto_rawDescData)
	})
	return file_cinema_service_v1_messages_proto_rawDescData
}

var file_cinema_service_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_cinema_service_v1_messages_proto_goTypes = []interface{}{
	(*Timestamp)(nil),                          // 0: cinema_service.Timestamp
	(*GetMoviesScreeningsRequest)(nil),         // 1: cinema_service.GetMoviesScreeningsRequest
	(*GetMoviesScreeningsInCitiesRequest)(nil), // 2: cinema_service.GetMoviesScreeningsInCitiesRequest
	(*Price)(nil),                              // 3: cinema_service.Price
	(*PreviewScreening)(nil),                   // 4: cinema_service.PreviewScreening
	(*PreviewScreenings)(nil),                  // 5: cinema_service.PreviewScreenings
	(*GetScreeningsRequest)(nil),               // 6: cinema_service.GetScreeningsRequest
	(*Screening)(nil),                          // 7: cinema_service.Screening
	(*Screenings)(nil),                         // 8: cinema_service.Screenings
	(*GetCinemasInCityRequest)(nil),            // 9: cinema_service.GetCinemasInCityRequest
	(*Coordinates)(nil),                        // 10: cinema_service.Coordinates
	(*Cinema)(nil),                             // 11: cinema_service.Cinema
	(*Cinemas)(nil),                            // 12: cinema_service.Cinemas
	(*City)(nil),                               // 13: cinema_service.City
	(*Cities)(nil),                             // 14: cinema_service.Cities
	(*Hall)(nil),                               // 15: cinema_service.Hall
	(*Halls)(nil),                              // 16: cinema_service.Halls
	(*GetCinemaRequest)(nil),                   // 17: cinema_service.GetCinemaRequest
	(*GetHallsRequest)(nil),                    // 18: cinema_service.GetHallsRequest
	(*GetHallConfigurationRequest)(nil),        // 19: cinema_service.GetHallConfigurationRequest
	(*Place)(nil),                              // 20: cinema_service.Place
	(*HallConfiguration)(nil),                  // 21: cinema_service.HallConfiguration
	(*GetCinemaHalls)(nil),                     // 22: cinema_service.GetCinemaHalls
}
var file_cinema_service_v1_messages_proto_depIdxs = []int32{
	0,  // 0: cinema_service.GetMoviesScreeningsRequest.startPeriod:type_name -> cinema_service.Timestamp
	0,  // 1: cinema_service.GetMoviesScreeningsRequest.endPeriod:type_name -> cinema_service.Timestamp
	0,  // 2: cinema_service.GetMoviesScreeningsInCitiesRequest.startPeriod:type_name -> cinema_service.Timestamp
	0,  // 3: cinema_service.GetMoviesScreeningsInCitiesRequest.endPeriod:type_name -> cinema_service.Timestamp
	4,  // 4: cinema_service.PreviewScreenings.screenings:type_name -> cinema_service.PreviewScreening
	0,  // 5: cinema_service.GetScreeningsRequest.startPeriod:type_name -> cinema_service.Timestamp
	0,  // 6: cinema_service.GetScreeningsRequest.endPeriod:type_name -> cinema_service.Timestamp
	0,  // 7: cinema_service.Screening.startTime:type_name -> cinema_service.Timestamp
	3,  // 8: cinema_service.Screening.ticketPrice:type_name -> cinema_service.Price
	7,  // 9: cinema_service.Screenings.screenings:type_name -> cinema_service.Screening
	10, // 10: cinema_service.Cinema.coordinates:type_name -> cinema_service.Coordinates
	11, // 11: cinema_service.Cinemas.cinemas:type_name -> cinema_service.Cinema
	13, // 12: cinema_service.Cities.cities:type_name -> cinema_service.City
	15, // 13: cinema_service.Halls.halls:type_name -> cinema_service.Hall
	20, // 14: cinema_service.HallConfiguration.place:type_name -> cinema_service.Place
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cinema_service_v1_messages_proto_init() }
func file_cinema_service_v1_messages_proto_init() {
	if File_cinema_service_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cinema_service_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviesScreeningsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMoviesScreeningsInCitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Price); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreviewScreening); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreviewScreenings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScreeningsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Screening); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Screenings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCinemasInCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cinema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cinemas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Halls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCinemaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHallsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHallConfigurationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HallConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_service_v1_messages_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCinemaHalls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cinema_service_v1_messages_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cinema_service_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cinema_service_v1_messages_proto_goTypes,
		DependencyIndexes: file_cinema_service_v1_messages_proto_depIdxs,
		MessageInfos:      file_cinema_service_v1_messages_proto_msgTypes,
	}.Build()
	File_cinema_service_v1_messages_proto = out.File
	file_cinema_service_v1_messages_proto_rawDesc = nil
	file_cinema_service_v1_messages_proto_goTypes = nil
	file_cinema_service_v1_messages_proto_depIdxs = nil
}
